---
title: "Appendix"
author: "Peter Hickey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
    includes:
      in_header: ../latex/header.tex
    keep_tex: no
  html_document:
    keep_md: yes
bibliography: ../latex/phd_thesis.bib
---

\chapter{Appendix}\label{chap:appendix}

\section{The probability that two dependent Bernoulli random variables are identical}\label{app:bernoulli_equal}

\cite{Lindqvist:1978fm} wrote a brief note on Bernoulli trials with dependence.
Building on earlier work by \cite{Klotz:1973if}, Lindqvist parameterises the
Bernoulli process $X_{1}, X_{2}, \ldots$ on $\{0, 1\}$ by the parameters
$p = Pr(X_{i} = 1)$ and $c = cor(X_{i - 1}, X_{i})$ and shows that the
transition matrix is given by

\begin{equation*}
\label{eq:transition_matrix_id}
\Pi =
 \begin{pmatrix}
  (1 - p) + cp & p (1 - c) \\
  (1 - p) (1 - c) & p + c (1 - p)
 \end{pmatrix}
\end{equation*}

provided that $max(1 - \frac{1}{p}, 1 - \frac{1}{1 - p}) \leq c \leq 1$.

From this we can compute the joint distribution,

\begin{align*}
 &  Pr(X_{1} = x_{1}, \ldots, X_{n} = x_{n}) \\
=& Pr(X_{1} = x_{1}) Pr(X_{2} = x_{2} | X_{2} = x_{2}) \cdots Pr(X_{n} = x_{n} | X_{n - 1} = x_{n - 1})
\end{align*}

In particular, in the case $n = 2$ we can compute the probability that two
dependent and identically distributed Bernoulli random variables are equal.

To extend the above result to the probability that two dependent and
__non-identically__ distributed Bernoulli random variables are equal, simply
requires that we derive the appropriate transition matrix. Switching notation
to that used in Chapter \ref{chap:co-methylation_review}, let
$Z_{h, i} \eqd Bernoulli(p_{h})$ and $Z_{h', i'} \eqd Bernoulli(p_{h'})$. The
transition matrix,
$\Pi = \bigl(\begin{smallmatrix}
Pr(Z_{h', i'} = z_{h', i'} | Z_{h, i} = z_{h, i})
\end{smallmatrix} \bigr)$, is given by

\begin{equation*}
\label{eq:transition_matrix_nid}
\Pi =
 \begin{pmatrix}
  (1 - p_{h'}) +c p_{h} & p_{h'} -c p_{h} \\
  (1 - p_{h'}) -c (1 - p_{h}) & p_{h'} + c (1 - p_{h})
 \end{pmatrix}
\end{equation*}

We can then compute the desired probability

\begin{align*}
Pr(Z_{h, i} = Z_{h', i'}) &= Pr(Z_{h, i} = 0, Z_{h', i'} = 0) + Pr(Z_{h, i} = 1, Z_{h', i'} = 1) \\
                  &= Pr(Z_{h', i'} = 0 | Z_{h, i} = 0) Pr(Z_{h, i} = 0) \\
                  &+ Pr(Z_{h', i'} = 1 | Z_{h, i} = 1) Pr(Z_{h, i} = 1) \\
                  &= \big [ (1 - p_{h'}) + c p_{h} \big ] (1 - p_{h}) +
                     \big [ p_{h'} + c ( 1 - p_{h}) \big ] p_{h} \\
                  &= (1 - p_{h}) (1 - p_{h'}) + c p_{h} \big [1 - p_{h}] +
                     p_{h} p_{h'} + c p_{h} (1 - p_{h}) \\
                  &= (1 - p_{h}) (1 - p_{h'}) + p_{h} p_{h'} + 2 c p_{h} (1 - p_{h})
\end{align*}

\section{Computing details}\label{app:computing_details}

All computational work was performed on one of the Bioinformatics Division's HP Blade servers. These are shared-use, shared-memory machines. The basic specifications are shown in Table \ref{tab:unices}.

\begin{table}[h]
\centering
\caption{Bioinformatics Division server specifications.}
\label{tab:unices}
\begin{tabulary}{\textwidth}{LLLL}
\toprule
Machine name & Processors & Number of cores & RAM    \\ \midrule
unix88       & $4\times$ Intel Xeon X7350 @ 2.93GHz & 16 & 128 GB \\
unix301      & $4\times$ AMD Opteron 8435 @ 2.6GHz  & 24 & 256 GB \\
unix302      & $4\times$ AMD Opteron 6174 @ 2.2GHz  & 48 & 512 GB \\
unix303      & $4\times$ AMD Opteron 6176 @ 2.3GHz  & 48 & 512 GB \\
unix305      & $4\times$ AMD Opteron 6276 @ 2.3GHz  & 64 & 512 GB \\ \bottomrule
\end{tabulary}
\end{table}

\section{Software details}\label{app:software_details}

The analyses described in my thesis made extensive use of R (`R Under development (unstable) (2014-10-29 r66891)` and `R version 3.2.0 (2015-04-16)`) and Python (`v2.7`). All analyses were run on one of the servers described above. The scripts used to prepare the results for each chapter are available from \url{https://github.com/PeteHaitch/phd_thesis_analyses}.

I developed several pieces of software during my PhD. These are listed below, along with the version used in for analyses in my thesis:

- `methtuple` (`v1.4.0`)
- `GenomicTuples` (`v1.2.1`)
- `MethylationTuples` (`v0.3.0.9007`, commit `4e127d2`)
- `methsim` (`v0.5.0.9013`, commit `9162c8b`)

In addition, I made use of the R packages listed in Table \ref{tab:R_packages} and gratefully acknowledge the developers.

```{r R_packages, echo = FALSE, eval = TRUE, message = FALSE, results = "asis"}
library(xtable)
x <- read.table("../data/r_packages.txt",  header = TRUE,
                stringsAsFactors = FALSE, sep = "\t")
# Drop packages with "*" column set, which indicates the package is a
# "dependency of a dependency".
x <- x[x[, 2] != "*", ]
x <- x[, -c(2, 4)]
# Drop MethylationTuples and methsim which are reported elsewhere
x <- x[!x$package %in% c("methsim", "MethylationTuples", "GenomicTUples"), ]
xt <- xtable(x, caption = c("R packages used in thesis (as reported by \\texttt{devtools::session\\_info()})", "R packages used in thesis"),
             label = "tab:R_packages")
align(xt) <- rep("l", 4)
print(xt, booktabs = TRUE, comment = FALSE, tabular.environment = "longtable",
      floating = FALSE, include.rownames = FALSE, caption.placement = "top")
```
