---
title: "Concluding remarks"
output:
  pdf_document:
    fig_caption: yes
    includes:
      in_header: ../latex/header.tex
  html_document:
    keep_md: true
bibliography: ../latex/phd_thesis.bib
---

\chapter{Concluding remarks}\label{chap:concluding_remarks}

This thesis has examined the statistical and computational challenges raised by high-throughput assays of DNA methylation. The first chapter introduced DNA methylation and then extensively reviewed different high-throughput assays for measuring it, focusing on the current gold standard assay of whole-genome bisulfite-sequencing.

The second chapter detailed the bioinformatics analysis of whole-genome bisulfite-sequencing data. Beginning with the `FASTQ` files created by the DNA sequencers, we reviewed the quality control procedures, read mapping, and post-processing steps that are essential to creating a `BAM` file containing high-quality mapped reads. We then described methods for calling methylation events from bisulfite-sequencing data. The chapter concluded by introducing m-tuples and the `methtuple` software that I wrote. Uniquely, `methtuple` can call methylation patterns at m-tuples from whole-genome bisulfite-sequencing data.

The third chapter described the 40 whole-genome bisulfite-sequencing samples that are analysed throughout the remainder of the thesis.

Chapter \ref{chap:wgbs_statistical_framework} laid out a statistical framework for analysing bisulfite-sequencing data. This process illustrated that the commonly used summary of methylation levels, the $\beta$-value, aggregates over many potential sources of variation. In light of this, we discussed the interpretation of $\beta$-values and examined the distributions of $\beta$-values in our 40 samples.

Chapter \ref{chap:wgbs_downstream_analyses} examined methods for analysing bisulfite-sequencing data to address key biological questions. Most downstream analyses are based on $\beta$-values, such as the identification of differential methylation, and we reviewed these. There is, however, a growing interest in analyses based on methylation patterns at m-tuples since these can address novel biological questions. A limitation to the development of these methods has been a lack of software. The chapter concluded with the development of the `MethylationTuples` R package, which, together with `methtuple`, is designed to facilitate analyses based on methylation patterns at m-tuples.

The sixth and seventh chapters are a comprehensive review and analysis of co-methylation, the spatial dependence of DNA methylation. Chapter \ref{chap:co-methylation_review} re-examined previous analyses of co-methylation and found that these have been limited by inadequate data and deficiencies in the statistical methods applied. We addressed some of these limitations with an extensive analysis of co-methylation in Chapter \ref{chap:co-methylation}. We proposed a novel analysis of co-methylation using methylation patterns from individual DNA fragments, which we call within-fragment co-methylation. A simulation study demonstrated that, in general, we cannot estimate this within-fragment co-methylation for individual pairs of CpGs. By aggregating pairs of CpG, however, the simulation study showed that we can estimate a summary of this spatial dependence of DNA methylation along individual DNA fragments. We applied this method to 40 whole-genome bisulfite-sequencing samples to identify genomic features that influence co-methylation and examined how it varies between different tissues.

To conclude, Chapter \ref{chap:methsim} detailed our efforts to develop the `methsim` software to simulate whole-genome bisulfite-sequencing data. Unlike existing software, `methsim` seeks to model co-methylation so as to create more realistic simulated data. Such simulated data will be useful in developing and benchmarking methods for the analysis of DNA methylation data. While aspects of `methsim` are promising, the overly-strong correlations of $\beta$-values is an obvious inadequacy in the current model. We continue to work to improve this and to develop the software more generally.

DNA methylation data have a complex dependence structure, as demonstrated by the analyses presented in this thesis. Any analysis must bear in mind the multiple sources of variation in the data and the amount of aggregation required in order to extract meaningful results.

The large size of the data generated by these experiments can make it challenging to develop analysis methods. This is particularly true when coupled with a lack of software for extracting, manipulating and summarising the relevant features of the data. Much of the effort in this thesis has gone into developing software to extract and manage this information (`methtuple` and `MethylationTuples`) so that new tools can be built on a higher foundation (`methsim`). It is my hope that, with continued development, these tools may facilitate other analyses to unravel the complexity of DNA methylation and its many biological roles.
